name: Bug Report
description: Report a bug or issue with the scripts, tools, or repository infrastructure
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form to help us identify and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component has the bug?
      options:
        - CSV conversion script
        - File validation script
        - Build/compilation tools
        - Web editor
        - Repository structure
        - Documentation
        - GitHub workflows/CI
        - Other
      multiple: false
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug
      placeholder: "Describe what's wrong and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Run command '...'
        2. Open file '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe the expected outcome"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually occurred"
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: If applicable, provide any error messages or logs
      placeholder: "Paste error messages here"
      render: shell
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
      multiple: false
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the operating system?
      placeholder: "e.g., Windows 11, macOS 14.2, Ubuntu 22.04"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide any other relevant environment information
      placeholder: |
        - Node/Bun Runtime Version
        - Package manager: npm/yarn/bun/pnpm
        - Shell: bash/zsh/powershell
        - Any other relevant tools or versions
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: "Drag and drop images here"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I am using the latest version of the scripts/tools
          required: true
