// Copyright (c) 2026 alepouna
// SPDX-License-Identifier: MIT
// Project: https://github.com/alepouna/vtolvr-polyglot

// Category JSON key -> CSV base filename (as generated by VTOL when creating a new loc)
export const CATEGORY_MAP: Record<string, string> = {
  av42c: "AV-42C",
  f45a: "F-45A",
  fa26b: "FA-26B",
  loadingSceneCanvas: "LoadingScene.Canvas",
  readyRoomInteractableCanvas: "ReadyRoom.InteractableCanvas",
  recenterCanvas: "RecenterCanvas",
  samplerSceneMain: "SamplerScene.main",
  vehicleConfigurationMissionLauncher: "VehicleConfiguration.MissionLauncher",
  vtolvrStrings: "VTOLVR_Strings",
  vtWorkshopListEntry: "VTWorkshopListEntry",
};
